seed: 2
slurm:
  partition: STUD
  time: 01:00:00
  mem_gb: 32
  cpus: 4
  gpus: 1
  job_name: base_point
  conda_env: thesis
data:
  csv_path: /home/canelo/uncertainty_quantification/datasets/craigslist_cleaned.csv
  target_col: price
  target_transform: none
  split_seed: 2
  split_fracs:
  - 0.7
  - 0.1
  - 0.2
  batch_size: 512
  num_workers: 2
  pin_memory: true
  shuffle_train: true
model:
  head_type: point
  hidden_dims:
  - 768
  - 384
  - 192
  activation: gelu
  dropout: 0.15000000000000002
  batchnorm: false
training:
  device: cuda
  epochs: 200
  lr: 0.000991201652360328
  weight_decay: 9.207710936904885e-06
  grad_clip: 0.9
  point_loss: huber
  eval_after_train: true
  early_stopping:
    enabled: true
    patience: 30
    min_delta: 0.0
objective: val_mae_orig
io:
  outdir: /home/canelo/uncertainty_quantification/outputs/trainings/training_base_point_2_20251122-1307/base_point_s1_20251122-210424_284572
  evals_root: outputs/evals/
  training_outdir: /home/canelo/uncertainty_quantification/outputs/trainings/training_base_point_2_20251122-1307/base_point_s2_20251122-210430
