seed: 3
slurm:
  partition: STUD
  time: 01:00:00
  mem_gb: 32
  cpus: 4
  gpus: 1
  job_name: base_point
  conda_env: thesis
data:
  csv_path: /home/canelo/uncertainty_quantification/datasets/craigslist_cleaned.csv
  target_col: price
  target_transform: none
  split_seed: 42
  split_fracs:
  - 0.7
  - 0.1
  - 0.2
  batch_size: 512
  num_workers: 2
  pin_memory: true
  shuffle_train: true
model:
  head_type: point
  hidden_dims:
  - 512
  - 512
  - 256
  activation: relu
  dropout: 0.15000000000000002
  batchnorm: false
training:
  device: cuda
  epochs: 100
  lr: 0.0010589412894325074
  weight_decay: 0.0015452752076576546
  grad_clip: 0.9
  point_loss: mse
  eval_after_train: false
  early_stopping:
    enabled: true
    patience: 30
    min_delta: 0.0
objective: val_mae_orig
io:
  outdir: .
  evals_root: outputs/evals/
  training_outdir: outputs/trainings/{job_name}
