seed: 3
slurm:
  partition: STUD
  time: 01:00:00
  mem_gb: 32
  cpus: 4
  gpus: 1
  job_name: prune_new_ds_base_point
  conda_env: thesis
data:
  csv_path: /home/canelo/uncertainty_quantification/datasets/craigslist_cleaned.csv
  target_col: price
  target_transform: none
  split_seed: 42
  split_fracs:
  - 0.7
  - 0.1
  - 0.2
  batch_size: 512
  num_workers: 2
  pin_memory: true
  shuffle_train: true
model:
  head_type: point
  hidden_dims:
  - 512
  - 512
  - 256
  activation: gelu
  dropout: 0.15000000000000002
  batchnorm: true
training:
  device: cuda
  epochs: 300
  lr: 0.000786449995503964
  weight_decay: 1.1862920129975062e-06
  grad_clip: 0.30000000000000004
  point_loss: mae
  eval_after_train: true
  early_stopping:
    enabled: true
    patience: 30
    min_delta: 0.0
objective: val_mae_orig
io:
  outdir: /home/canelo/uncertainty_quantification/outputs/trainings/training_prune2_new_ds_base_point_20251120-1706/point_300_epochs_200ep_s1_20251121-095142
  evals_root: outputs/evals/
  training_outdir: /home/canelo/uncertainty_quantification/outputs/trainings/training_prune2_new_ds_base_point_20251120-1706/point_300_epochs_200ep_s1_20251121-095142
